version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8000:80"
    command: ["nginx", "-g", "daemon off;"]
